name: ct484_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  intl: ^0.19.0
  http: ^1.3.0
  html_unescape: ^2.0.0
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  pocketbase: ^0.22.0
  image_picker: ^1.1.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  just_audio: ^0.9.36
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/background_music.mp3
    - assets/audio/correct_answer.mp3
    - assets/audio/wrong_answer.mp3
    - assets/audio/quiz_complete.mp3
    - .env

flutter_launcher_icons: #icon
  android: true
  ios: false
  image_path: "assets/icon.png"
